export const CANVAS_PRESETS = [
  { id: 'square', label: 'Instagram Quadrat', width: 1080, height: 1080 },
  { id: 'portrait', label: 'Instagram Portrait', width: 1080, height: 1350 },
  { id: 'story', label: 'Story / Reel', width: 1080, height: 1920 },
  { id: 'landscape', label: 'Landscape Feed', width: 1080, height: 566 },
];

export const COLOR_PRESETS = [
  { id: 'pink-lila', label: 'Pink / Lila', background: '#D562EB', frame: '#000000', placeholder: '#1E1E1A', accent: '#FFFFFF' },
  { id: 'tuerkis-lila', label: 'Türkis / Lila', background: '#00FDFF', frame: '#000000', placeholder: '#22221F', accent: '#9933FF' },
  { id: 'gelb-schwarz', label: 'Gelb / Schwarz', background: '#FFF500', frame: '#000000', placeholder: '#1E1E1A', accent: '#000000' },
  { id: 'blau-weiss', label: 'Blau / Weiß', background: '#3355FF', frame: '#FFFFFF', placeholder: '#111111', accent: '#FFFFFF' },
  { id: 'orange-weiss', label: 'Orange / Weiß', background: '#FF6E00', frame: '#FFFFFF', placeholder: '#1C1711', accent: '#FFFFFF' },
  { id: 'gruen-schwarz', label: 'Grün / Schwarz', background: '#00FF0A', frame: '#000000', placeholder: '#141A14', accent: '#000000' },
  { id: 'schwarz-weiss', label: 'Schwarz / Weiß', background: '#000000', frame: '#FFFFFF', placeholder: '#202020', accent: '#FFFFFF' },
  { id: 'weiss-blau', label: 'Weiß / Blau', background: '#FFFFFF', frame: '#3355FF', placeholder: '#202020', accent: '#3355FF' },
];

export const LOGO_PRESETS = [
  {
    id: 'digilab-kombi',
    name: 'DigiLab.ai Kombi',
    src: '/logos/digilab-ai-kombi-black.png',
    defaults: {
      tint: '#FFFFFF',
      preserveColor: false,
      removeWhite: true,
      whiteThreshold: 240,
    },
  },
  {
    id: 'bildmarke',
    name: 'DigiLab.ai Bildmarke',
    src: '/logos/dwd-bildmarke-blau.png',
    defaults: {
      tint: '#3355FF',
      preserveColor: false,
      removeWhite: true,
      whiteThreshold: 240,
    },
  },
];

export const MOTION_PRESETS = [
  {
    id: 'clean-loop',
    label: 'Clean Loop',
    mask: { turbulence: 0.08, complexity: 0.18, evolutionSpeed: 1, wobble: 0.05, asymmetry: 0.08, breath: 0.03 },
    imageMotion: { driftX: 0.035, driftY: 0.025, zoom: 0.05, zoomSpeed: 1, rotate: 1, rotateSpeed: 1, orbit: 0.012, orbitCycles: 1 },
  },
  {
    id: 'slow-loop',
    label: 'Slow Loop',
    mask: { turbulence: 0.1, complexity: 0.22, evolutionSpeed: 1, wobble: 0.08, asymmetry: 0.1, breath: 0.05 },
    imageMotion: { driftX: 0.05, driftY: 0.03, zoom: 0.07, zoomSpeed: 1, rotate: 1.5, rotateSpeed: 1, orbit: 0.02, orbitCycles: 1 },
  },
  {
    id: 'wild-loop',
    label: 'Wild Loop',
    mask: { turbulence: 0.32, complexity: 0.58, evolutionSpeed: 4, wobble: 0.24, asymmetry: 0.3, breath: 0.09 },
    imageMotion: { driftX: 0.14, driftY: 0.11, zoom: 0.16, zoomSpeed: 4, rotate: 7, rotateSpeed: 4, orbit: 0.08, orbitCycles: 3 },
  },
  {
    id: 'micro-wobble',
    label: 'Micro Wobble',
    mask: { turbulence: 0.06, complexity: 0.16, evolutionSpeed: 2, wobble: 0.035, asymmetry: 0.05, breath: 0.02 },
    imageMotion: { driftX: 0.018, driftY: 0.015, zoom: 0.03, zoomSpeed: 2, rotate: 0.7, rotateSpeed: 2, orbit: 0.008, orbitCycles: 2 },
  },
  {
    id: 'ae-classic',
    label: 'AE Classic',
    mask: { turbulence: 0.22, complexity: 0.46, evolutionSpeed: 2, wobble: 0.13, asymmetry: 0.17, breath: 0.04 },
    imageMotion: { driftX: 0.08, driftY: 0.05, zoom: 0.12, zoomSpeed: 2, rotate: 3, rotateSpeed: 1, orbit: 0.03, orbitCycles: 1 },
  },
  {
    id: 'soft-float',
    label: 'Soft Float',
    mask: { turbulence: 0.12, complexity: 0.28, evolutionSpeed: 1, wobble: 0.07, asymmetry: 0.1, breath: 0.06 },
    imageMotion: { driftX: 0.04, driftY: 0.025, zoom: 0.08, zoomSpeed: 1, rotate: 1.5, rotateSpeed: 1, orbit: 0.02, orbitCycles: 1 },
  },
  {
    id: 'liquid-roll',
    label: 'Liquid Roll',
    mask: { turbulence: 0.2, complexity: 0.34, evolutionSpeed: 2, wobble: 0.12, asymmetry: 0.24, breath: 0.05 },
    imageMotion: { driftX: 0.09, driftY: 0.08, zoom: 0.1, zoomSpeed: 2, rotate: 4.5, rotateSpeed: 2, orbit: 0.05, orbitCycles: 2 },
  },
  {
    id: 'rubber-pulse',
    label: 'Rubber Pulse',
    mask: { turbulence: 0.16, complexity: 0.24, evolutionSpeed: 2, wobble: 0.18, asymmetry: 0.14, breath: 0.1 },
    imageMotion: { driftX: 0.03, driftY: 0.03, zoom: 0.18, zoomSpeed: 3, rotate: 1.2, rotateSpeed: 1, orbit: 0.025, orbitCycles: 1 },
  },
  {
    id: 'storm-wave',
    label: 'Storm Wave',
    mask: { turbulence: 0.34, complexity: 0.6, evolutionSpeed: 3, wobble: 0.22, asymmetry: 0.28, breath: 0.07 },
    imageMotion: { driftX: 0.14, driftY: 0.09, zoom: 0.14, zoomSpeed: 2, rotate: 6, rotateSpeed: 3, orbit: 0.07, orbitCycles: 2 },
  },
];

export const MASK_PRESETS = [
  {
    id: 'post-form-01',
    label: 'Post Form 01',
    family: 'Form 01',
    format: 'square',
    width: 0.74,
    height: 0.74,
    stageY: 0.52,
    shapeScale: 0.92,
    squishX: 1.02,
    squishY: 1.08,
    pixelSize: 34,
    points: 18,
    turbulence: 0.2,
    complexity: 0.45,
    wobble: 0.13,
    asymmetry: 0.17,
    evolutionSpeed: 0.22,
  },
  {
    id: 'story-form-01',
    label: 'Story Form 01',
    family: 'Form 01',
    format: 'story',
    width: 0.76,
    height: 0.58,
    stageY: 0.54,
    shapeScale: 0.88,
    squishX: 1.06,
    squishY: 1.12,
    pixelSize: 30,
    points: 18,
    turbulence: 0.22,
    complexity: 0.48,
    wobble: 0.13,
    asymmetry: 0.17,
    evolutionSpeed: 0.22,
  },
  {
    id: 'post-form-02',
    label: 'Post Form 02',
    family: 'Form 02',
    format: 'square',
    width: 0.77,
    height: 0.77,
    stageY: 0.52,
    shapeScale: 1.0,
    squishX: 0.95,
    squishY: 1.12,
    pixelSize: 34,
    points: 14,
    turbulence: 0.18,
    complexity: 0.32,
    wobble: 0.1,
    asymmetry: 0.28,
    evolutionSpeed: 0.19,
  },
  {
    id: 'story-form-02',
    label: 'Story Form 02',
    family: 'Form 02',
    format: 'story',
    width: 0.76,
    height: 0.57,
    stageY: 0.55,
    shapeScale: 0.98,
    squishX: 0.95,
    squishY: 1.14,
    pixelSize: 30,
    points: 14,
    turbulence: 0.18,
    complexity: 0.32,
    wobble: 0.1,
    asymmetry: 0.28,
    evolutionSpeed: 0.19,
  },
  {
    id: 'post-form-03',
    label: 'Post Form 03',
    family: 'Form 03',
    format: 'square',
    width: 0.61,
    height: 0.73,
    stageY: 0.52,
    shapeScale: 0.86,
    squishX: 0.92,
    squishY: 1.15,
    pixelSize: 33,
    points: 17,
    turbulence: 0.14,
    complexity: 0.38,
    wobble: 0.09,
    asymmetry: 0.11,
    evolutionSpeed: 0.16,
  },
  {
    id: 'story-form-03',
    label: 'Story Form 03',
    family: 'Form 03',
    format: 'story',
    width: 0.55,
    height: 0.5,
    stageY: 0.56,
    shapeScale: 0.84,
    squishX: 0.93,
    squishY: 1.15,
    pixelSize: 28,
    points: 17,
    turbulence: 0.14,
    complexity: 0.38,
    wobble: 0.09,
    asymmetry: 0.11,
    evolutionSpeed: 0.16,
  },
  {
    id: 'post-form-04',
    label: 'Post Form 04',
    family: 'Form 04',
    format: 'square',
    width: 0.78,
    height: 0.78,
    stageY: 0.52,
    shapeScale: 1.04,
    squishX: 1.08,
    squishY: 1.08,
    pixelSize: 35,
    points: 12,
    turbulence: 0.16,
    complexity: 0.24,
    wobble: 0.18,
    asymmetry: 0.34,
    evolutionSpeed: 0.2,
  },
  {
    id: 'story-form-04',
    label: 'Story Form 04',
    family: 'Form 04',
    format: 'story',
    width: 0.79,
    height: 0.57,
    stageY: 0.55,
    shapeScale: 1.02,
    squishX: 1.09,
    squishY: 1.06,
    pixelSize: 31,
    points: 12,
    turbulence: 0.16,
    complexity: 0.24,
    wobble: 0.18,
    asymmetry: 0.34,
    evolutionSpeed: 0.2,
  },
  {
    id: 'wide-form',
    label: 'Wide Form',
    family: 'Wide',
    format: 'landscape',
    width: 0.82,
    height: 0.54,
    stageY: 0.53,
    shapeScale: 0.94,
    squishX: 1.12,
    squishY: 0.94,
    pixelSize: 28,
    points: 16,
    turbulence: 0.16,
    complexity: 0.4,
    wobble: 0.12,
    asymmetry: 0.16,
    evolutionSpeed: 0.18,
  },
];

export const FORM_MOTION_PRESETS = [
  { id: 'form01-clean', label: 'Form 01 Clean', maskPresetId: 'post-form-01', motionPresetId: 'clean-loop' },
  { id: 'form02-liquid', label: 'Form 02 Liquid', maskPresetId: 'post-form-02', motionPresetId: 'liquid-roll' },
  { id: 'form03-editorial', label: 'Form 03 Editorial', maskPresetId: 'post-form-03', motionPresetId: 'micro-wobble' },
  { id: 'form04-wild', label: 'Form 04 Wild', maskPresetId: 'post-form-04', motionPresetId: 'wild-loop' },
  { id: 'story01-clean', label: 'Story 01 Clean', maskPresetId: 'story-form-01', motionPresetId: 'clean-loop' },
  { id: 'story02-liquid', label: 'Story 02 Liquid', maskPresetId: 'story-form-02', motionPresetId: 'liquid-roll' },
  { id: 'story03-editorial', label: 'Story 03 Editorial', maskPresetId: 'story-form-03', motionPresetId: 'slow-loop' },
  { id: 'story04-wild', label: 'Story 04 Wild', maskPresetId: 'story-form-04', motionPresetId: 'wild-loop' },
];

export const createInitialScene = () => ({
  presetId: 'story',
  colorPresetId: 'pink-lila',
  motionPresetId: 'ae-classic',
  infoLayoutPresetId: 'aep-auto',
  backgroundColor: '#D562EB',
  useCustomBackground: false,
  imageSrc: '',
  imageName: '',
  playback: {
    playing: true,
    duration: 6,
    fps: 30,
    rate: 1,
    time: 0,
    loop: true,
  },
  guides: {
    showGrid: false,
    columns: 12,
    rows: 12,
    opacity: 0.24,
  },
  stage: {
    x: 0.5,
    y: 0.52,
    width: 0.78,
    height: 0.56,
    scale: 1,
    rotation: 0,
    fill: '#000000',
    shadow: 0,
    radius: 0,
    showBackdrop: false,
    backdropOpacity: 1,
  },
  mask: {
    presetId: 'story-form-01',
    shapeScale: 0.88,
    squishX: 1.06,
    squishY: 1.12,
    pixelSize: 30,
    points: 18,
    turbulence: 0.22,
    complexity: 0.48,
    evolutionSpeed: 2,
    wobble: 0.13,
    asymmetry: 0.17,
    breath: 0.04,
    seed: 4201,
    xOffset: 0,
    yOffset: 0,
  },
  imageMotion: {
    scale: 1.05,
    driftX: 0.08,
    driftY: 0.05,
    zoom: 0.12,
    zoomSpeed: 2,
    rotate: 3,
    rotateSpeed: 1,
    orbit: 0.03,
    orbitCycles: 1,
  },
  overlay: {
    showLogo: true,
    logoSrc: '/logos/digilab-ai-kombi-black.png',
    logoName: 'DigiLab.ai Kombi',
    logoTint: '#FFFFFF',
    preserveColor: false,
    removeWhite: true,
    whiteThreshold: 240,
    logoScale: 0.9,
    logoX: 0.92,
    logoY: 0.94,
  },
  infoLayer: {
    show: true,
    date: '00.00.',
    title1: 'Titel Zeile 1',
    title2: 'Titel Zeile 2',
    start: 'Start:',
    duration: 'Dauer:',
    location: 'Ort/Raum/Online',
    email: 'digilab.ai@fh-dortmund.de',
    titleColor: '#FFFFFF',
    metaColor: '#FFFFFF',
    emailColor: '#FFFFFF',
    dateColor: '#FFFFFF',
    dateSize: 48,
    titleSize: 56,
    metaSize: 26,
    emailSize: 32,
    weight: 500,
    dateX: 0.075,
    dateY: 0.042,
    titleX: 0.315,
    titleY: 0.042,
    metaX: 0.315,
    metaY: 0.155,
    eventX: 0.04,
    eventY: 0.05,
    emailX: 0.075,
    emailY: 0.925,
  },
});
